name: CI

on:
  push:
    branches-ignore:
    - 'l10n_master'
    - 'gh-pages'
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+-*'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      imgur_client_id: ${{ secrets.imgur_client_id }}
      yt_client_id: ${{ secrets.yt_client_id }}
      yt_client_secret: ${{ secrets.yt_client_secret }}
      choco_key: ${{ secrets.choco_key }}

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Cake
      run: dotnet tool install -g Cake.Tool --version 0.32.1
    - name: Install Inno Setup
      run: choco install innosetup -y

    - name: Generate build number
      if: (!startsWith(github.ref, 'refs/tags/'))
      uses: einaregilsson/build-number@v1 
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Cake script (CI)
      if: (!startsWith(github.ref, 'refs/tags/'))
      run: |
        echo ::set-env name=CHOCO_VERSION::0.0.%BUILD_NUMBER%
        dotnet-cake --build_version=v0.0.%BUILD_NUMBER%

    - name: Extract Tag
      if: startsWith(github.ref, 'refs/tags/')
      # remove /ref/tags/ to get tag name
      run: |
        echo ::set-env name=GIT_TAG::$(echo ${GITHUB_REF:10})
        echo ::set-env name=CHOCO_VERSION::$(echo ${GITHUB_REF:11})
    - name: Run Cake script (Release)
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet-cake --build_version=%GIT_TAG%
   
    - name: Upload Portable build to artifacts
      uses: actions/upload-artifact@master
      with:
        name: Portable
        path: temp/Captura-Portable.zip
    - name: Upload Setup build to artifacts
      uses: actions/upload-artifact@master
      with:
        name: Setup
        path: temp/Captura-Setup.exe

    - name: Upload Chocolatey Package to artifacts
      uses: actions/upload-artifact@master
      with:
        name: Chocolatey
        path: temp/captura.${{ env.CHOCO_VERSION }}.nupkg

  deploy-gh-releases:
    name: Deploy to GitHub Releases
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download Portable build
      uses: actions/download-artifact@v1
      with:
        name: Portable
    - name: Download Setup build
      uses: actions/download-artifact@v1
      with:
        name: Setup
    - name: Deploy to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Setup/Captura-Setup.exe
          Portable/Captura-Portable.zip
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-choco:
    name: Deploy to Choclatey
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download Chocolatey Package
      uses: actions/download-artifact@v1
      with:
        name: Chocolatey
    - name: Deploy to Chocolatey
      run: |
        cd Chocolatey
        choco push --source https://push.chocolatey.org/ -y --key %choco_key%
        cd ..